spring.application.name: fleet-taxi-service

server.error.include-message: on_param
server.port: 8082

# LOGGING
##########
logging.level.root: info

# RABBITMQ
##########
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: pass

# SERVICE
##########
rabbitmq:
  booking:
    exchange-name: ${BOOKING_EXCHANGE:booking-exchange}
    request:
      routing-key: ${BOOKING_REQUEST_ROUTE:booking-request-route}
      queue-name: ${BOOKING_REQUEST_QUEUE:booking-request-queue-taxi-n}
  taxi:
    exchange-name: ${TAXI_EXCHANGE:taxi-exchange}
    status:
      routing-key: ${TAXI_STATUS_ROUTE:taxi-status-route}
    claim:
      routing-key: ${TAXI_CLAIM_ROUTE:taxi-claim-route}

taxi:
  name: ${TAXI_NAME:taxi-n}
  seats: ${TAXI_SEATS:3}
  initial-state: ${TAXI_INITIAL_STATUS:AVAILABLE}
  initial-longitude: ${TAXI_INITIAL_LONGITUDE:-58.4745003}
  initial-latitude: ${TAXI_INITIAL_LATITUDE:-34.579444}
