spring.application.name: fleet-booking-service

server.error.include-message: on_param
server.port: 8081

# LOGGING
##########
logging.level.root: info

# RABBITMQ
##########
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: pass

# SERVICE
##########
rabbitmq:
  booking:
    exchange-name: ${BOOKING_EXCHANGE:booking-exchange}
    request:
      routing-key: ${BOOKING_REQUEST_ROUTE:booking-request-route}
  taxi:
    exchange-name: ${TAXI_EXCHANGE:taxi-exchange}
    status:
      routing-key: ${TAXI_STATUS_ROUTE:taxi-status-route}
      queue-name: ${TAXI_STATUS_QUEUE:taxi-status-queue}
    claim:
      routing-key: ${TAXI_CLAIM_ROUTE:taxi-claim-route}
      queue-name: ${TAXI_CLAIM_QUEUE:taxi-claim-queue}
